- students/0/readme.md
Update readme with my name, this is just for illustration purposes.
> Update readme with my name

- students/2/readme.md
> Dev af update readme

- students/3/readme.md
> Update Favorite Color

- students/6/readme.md
> Dev js update color

- students/6/readme.md
> Dev js yummy food

- students/3/readme.md
> Add Favorite Food

- students/1/readme.md
> update favorite food

- students/3/readme.md
> Update Favorite Band

- students/3/readme.md
> Update Favorite Holiday

- students/3/readme.md
> Update Favorite Season

- students/2/modern-js.js
> Dev af ex0

- students/8/main.js
- Declare array values
- Initialize storage variable
- Setup loop through array
- If statement with double logical operator to check only numbers for lowest value
- Set storage variable value to current array member if lower than previous
- Return storage variable once array cycle is complete
> Ex2 Min Number

- students/6/main.js
> Ex2: minNum

- students/8/main.js
- Declare array members
- Set lgth variable to length of the first string
- Initialize storage variable
- Set loop
- Compare current string length to stored string length
- Set lgth variable to length of current string if shorter than
- Store current string length if lesser than previous stored length
- Once loop is complete, output the shortest string
> Ex3 Shortest String

- students/3/main.js
> Ex2: Smallest Number

- students/8/main.js
Set a loop to step through array and count the number of letters in each string in the array.  
Output the total.
> Ex4 Count Letters

- students/1/main.js
I sorted the array from longest string to shortest string and substract the return value by 5 to get the shortest string.
> Ex. 3 - Shortest String

- students/8/main.js
Count types of different elements in an array and output the number of occurrences of those elements.
> Ex5 Count Types

- students/3/hw.js
- students/3/main.js
Identify shortest string in array.
> Ex3: Shortest String

- students/9/main.js
> ex4 count numbers 

- .gitignore
- students/8/main.js
Count types of different elements in an array and output the number of occurrences of those elements.
> Ex6 Count Types

- .gitignore
- students/8/main.js
Push a list of people into an object, then sort by age.
Display in table format
> Ex7 People Object & Table

- students/8/main.js
Created a function to assign property names to input.
Then count the number of entries with an age < 20 in the array.
> Ex8 Counting <20

- students/10/main.js
push person objects based on age in ascending order
> Ex7: push method

- students/8/main.js
Push item arrays into an object then calculate the total.
> Ex9 Calculate Total

- students/10/main.js
push array to count people over the age of 20
> Ex8: countOver20

- students/1/main.js
1. First I created an array.
2. Then I sorted the data ascending by age
3. Finally I created a table with all of the data included
> Ex. 7 - Turning an array into a table

- students/6/main.js
1. Push Method
2. People Array
> Ex 7: Push Method

- students/8/main.js
Calculate cell bill by pulling individual's cell usage from multiuser array, calculate charges, then return all of individual's information.
> Ex 10 Cell Bill for Person

- students/10/main.js
use JavaScript object to calculate bill
> Ex10: calcCellBillForPerson

- students/1/ShoppingCart.js
- students/1/main.js
> I started off by pushing the objects into an array
> Created a function called calculateTotal then created a for loop inside to loop through the array and adding and multiply and adding the quantity and the cost to get the end result.
> Ex. 9 - Calculate Total
